USE db_maior_sj_mundo;

-- SET FOREIGN_KEY_CHECKS = 0;
-- 
-- TRUNCATE TABLE tb_genero_musical;
-- 
-- SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO TB_GENERO_MUSICAL (DESCRICAO) VALUES
('Música Popular e Internacional'),
('Pop'),
('Dance Pop'),
('Synthpop'),
('Electropop'),
('Teen Pop'),
('Indie Pop'),
('Pop Rock'),
('Art Pop'),
('Chamber Pop'),
('Dream Pop'),
('Hyperpop'),
('K-Pop'),
('J-Pop'),
('C-Pop'),
('Rock'),
('Rock and Roll'),
('Rock Clássico'),
('Hard Rock'),
('Soft Rock'),
('Arena Rock'),
('Glam Rock'),
('Progressive Rock'),
('Psychedelic Rock'),
('Alternative Rock'),
('Indie Rock'),
('Garage Rock'),
('Punk Rock'),
('Pop Punk'),
('Post-Punk'),
('Post-Rock'),
('Folk Rock'),
('Southern Rock'),
('Surf Rock'),
('Grunge'),
('Gothic Rock'),
('Stoner Rock'),
('Noise Rock'),
('Math Rock'),
('Shoegaze'),
('Metal'),
('Heavy Metal'),
('Thrash Metal'),
('Death Metal'),
('Black Metal'),
('Power Metal'),
('Symphonic Metal'),
('Doom Metal'),
('Progressive Metal'),
('Folk Metal'),
('Viking Metal'),
('Melodic Death Metal'),
('Groove Metal'),
('Nu Metal'),
('Speed Metal'),
('Industrial Metal'),
('Metalcore'),
('Deathcore'),
('Grindcore'),
('Blues'),
('Delta Blues'),
('Chicago Blues'),
('Texas Blues'),
('Electric Blues'),
('Country Blues'),
('Blues Rock'),
('Piedmont Blues'),
('Jump Blues'),
('Jazz'),
('Traditional Jazz'),
('Swing'),
('Bebop'),
('Hard Bop'),
('Cool Jazz'),
('Free Jazz'),
('Fusion'),
('Smooth Jazz'),
('Latin Jazz'),
('Jazz Funk'),
('Gypsy Jazz'),
('Acid Jazz'),
('Vocal Jazz'),
('Música Clássica'),
('Barroco'),
('Clássico'),
('Romântico'),
('Impressionista'),
('Contemporâneo'),
('Ópera'),
('Música de Câmara'),
('Coral'),
('Sinfônica'),
('Minimalista'),
('Neoclássica'),
('Música Eletrônica'),
('House'),
('Deep House'),
('Tech House'),
('Progressive House'),
('Electro House'),
('Future House'),
('Techno'),
('Minimal Techno'),
('Detroit Techno'),
('Trance'),
('Psytrance'),
('Goa Trance'),
('Hard Trance'),
('Drum and Bass'),
('Jungle'),
('Dubstep'),
('Brostep'),
('UK Garage'),
('Breakbeat'),
('Big Beat'),
('Ambient'),
('Downtempo'),
('Chillout'),
('IDM'),
('Electro'),
('Synthwave'),
('Vaporwave'),
('Hardstyle'),
('Hardcore'),
('Gabber'),
('Hip-Hop e Rap'),
('Old School Rap'),
('Boom Bap'),
('Gangsta Rap'),
('Conscious Rap'),
('Trap'),
('Drill'),
('Mumble Rap'),
('Lo-Fi Hip Hop'),
('Jazz Rap'),
('Alternative Hip Hop'),
('Hardcore Rap'),
('East Coast Rap'),
('West Coast Rap'),
('R&B e Soul'),
('Rhythm and Blues (R&B)'),
('Contemporary R&B'),
('Soul'),
('Neo Soul'),
('Motown'),
('Funk'),
('Disco'),
('Quiet Storm'),
('Country'),
('Country Tradicional'),
('Country Pop'),
('Country Rock'),
('Bluegrass'),
('Honky Tonk'),
('Western Swing'),
('Outlaw Country'),
('Americana'),
('Música Latina'),
('Salsa'),
('Merengue'),
('Bachata'),
('Reggaeton'),
('Cumbia'),
('Tango'),
('Bolero'),
('Mariachi'),
('Ranchera'),
('Son Cubano'),
('Latin Pop'),
('Latin Rock'),
('Música Brasileira'),
('Samba'),
('Samba-Enredo'),
('Samba de Roda'),
('Pagode'),
('Partido Alto'),
('Choro'),
('Bossa Nova'),
('MPB'),
('Jovem Guarda'),
('Tropicália'),
('Axé'),
('Forró'),
('Forró Pé de Serra'),
('Forró Universitário'),
('Xote'),
('Baião'),
('Xaxado'),
('Arrasta-Pé'),
('Frevo'),
('Maracatu'),
('Coco'),
('Ciranda'),
('Manguebeat'),
('Sertanejo'),
('Sertanejo Raiz'),
('Sertanejo Universitário'),
('Moda de Viola'),
('Música Caipira'),
('Vanerão'),
('Chamamé'),
('Tchê Music'),
('Funk Carioca'),
('Funk Ostentação'),
('Funk Melody'),
('Brega'),
('Brega Funk'),
('Tecnobrega'),
('Piseiro'),
('Arrocha'),
('Sofrência'),
('Lambada'),
('Carimbó'),
('Guitarrada'),
('Música Nordestina'),
('Repente'),
('Cantoria'),
('Embolada'),
('Cavalo Marinho'),
('Toada'),
('Reisado'),
('Quadrilha Junina'),
('Forró Eletrônico'),
('Música Religiosa'),
('Gospel'),
('Worship'),
('Louvor'),
('Música Litúrgica'),
('Música Sacra'),
('Canto Gregoriano'),
('Gospel Rock'),
('Gospel Pop'),
('Gospel Pentecostal'),
('Música Folclórica e Tradicional'),
('Folk'),
('Folk Contemporâneo'),
('Celtic'),
('Música Andina'),
('Flamenco'),
('Fado'),
('Klezmer'),
('Polca'),
('Valsa'),
('Tarantela'),
('Música Africana'),
('Afrobeat'),
('Highlife'),
('Juju'),
('Mbalax'),
('Soukous'),
('Afro House'),
('Amapiano'),
('Música Asiática'),
('Enka'),
('Gagaku'),
('Mandopop'),
('Cantopop'),
('Trot'),
('City Pop'),
('Música Experimental'),
('Avant-Garde'),
('Noise'),
('Musique Concrète'),
('Drone'),
('Glitch'),
('Industrial'),
('Dark Ambient'),
('Trilhas e Instrumentais'),
('Soundtrack'),
('Cinematic'),
('Orquestral'),
('Instrumental'),
('New Age'),
('Easy Listening'),
('Lounge'),
('Gêneros Modernos e Híbridos'),
('Lo-Fi'),
('Bedroom Pop'),
('Chillhop'),
('Electro Swing'),
('Folktronica'),
('Indie Folk'),
('Country Trap'),
('Trap Metal'),
('Phonk'),
('Dark Trap'),
('Future Bass'),
('Wave'),
('Slap House'),
('Música Infantil'),
('Cantigas de Roda'),
('Música Educativa'),
('Canções Infantis'),
('Música Militar e Cerimonial'),
('Marcha Militar'),
('Dobrado'),
('Fanfarra'),
('Reggae'),
('Rap');