USE db_maior_sj_mundo;

-- SET foreign_key_checks = 0;
-- 
-- TRUNCATE TABLE tb_artista;
-- 
-- SET foreign_key_checks = 1;

INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Banda Magníficos', 'De Monteiro-PB, conhecida como a Preferida do Brasil','www.bandamagnificos.com.br','@magnificos');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Luiz Gonzaga', 'compositor e sanfoneiro brasileiro conhecido como Rei do Baião.','www.luizgonzaga.com.br','@luizgonzagaoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Dominguinhos','Cantor e instrumentista brasileiro considerado um dos maiores nomes da música nordestina.','www.dominguinhos.com.br','@dominguinhosoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Flávio José','Cantor e compositor paraibano referência do forró tradicional.','www.flaviojose.com.br','@flaviojoseoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Elba Ramalho','Cantora paraibana reconhecida nacionalmente por sua contribuição à música nordestina.','www.elbaramalho.com.br','@elbaramalho');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (183,'Santanna','Cantor cearense conhecido como O Cantador.','www.santanna.com.br','@santannaocantador');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (182,'Ivete Sangalo','Cantora baiana considerada uma das maiores artistas do Brasil.','www.ivetesangalo.com','@ivetesangalo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (182,'Claudia Leitte','Cantora brasileira de destaque no axé e na música pop.','www.claudialeitte.com','@claudialeitte');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (182,'Daniela Mercury','Cantora baiana reconhecida internacionalmente pelo axé music.','www.danielamercury.com.br','@danielamercury');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (182,'Bell Marques','Cantor brasileiro famoso por sua trajetória no Chiclete com Banana.','www.bellmarques.com.br','@bellmarques');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (182,'Durval Lelys','Cantor e compositor baiano conhecido pelo Asa de Águia.','www.durvallelys.com.br','@durvallelys');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (172,'Alcione','Cantora maranhense conhecida como A Marrom.','www.alcione.com.br','@alcioneamarrom');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (172,'Zeca Pagodinho','Cantor e compositor brasileiro ícone do samba.','www.zecapagodinho.com.br','@zecapagodinho');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (172,'Martinho da Vila','Cantor e compositor brasileiro de destaque no samba.','www.martinhodavila.com.br','@martinhodavila');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (172,'Jorge Aragão','Cantor e compositor brasileiro consagrado no samba.','www.jorgearagao.com.br','@jorgearagao');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (172,'Beth Carvalho','Cantora brasileira considerada madrinha do samba.','www.bethcarvalho.com.br','@bethcarvalho');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (175,'Thiaguinho','Cantor brasileiro conhecido por sua carreira solo e passagem pelo Exaltasamba.','www.thiaguinho.net','@thiaguinho');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (175,'Péricles','Cantor e compositor brasileiro referência do pagode.','www.pericles.com.br','@pericles');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (175,'Belo','Cantor brasileiro conhecido por sua carreira romântica no pagode.','www.belo.com.br','@belo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (175,'Ferrugem','Cantor brasileiro destaque do pagode contemporâneo.','www.ferrugem.com.br','@ferrugemoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (175,'Mumuzinho','Cantor e apresentador brasileiro de sucesso no pagode.','www.mumuzinho.com.br','@mumuzinho');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (2,'Michael Jackson','compositor e dançarino conhecido como Rei do Pop.','www.michaeljackson.com','@michaeljackson');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (2,'Madonna','Cantora norte-americana conhecida como Rainha do Pop.','www.madonna.com','@madonna');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (2,'Taylor Swift','Cantora e compositora norte-americana de enorme sucesso global.','www.taylorswift.com','@taylorswift');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (2,'Adele','Cantora britânica reconhecida por sua voz marcante.','www.adele.com','@adele');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (2,'Ed Sheeran','Cantor e compositor britânico de sucesso internacional.','www.edsheeran.com','@teddysphotos');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Elvis Presley','Cantor norte-americano conhecido como Rei do Rock.','www.elvis.com','@elvis');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Freddie Mercury','Vocalista da banda Queen e um dos maiores cantores da história.','www.queenonline.com','@officialqueenmusic');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Mick Jagger','Cantor britânico líder da banda Rolling Stones.','www.rollingstones.com','@mickjagger');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Bono','Vocalista da banda U2 e ativista humanitário.','www.u2.com','@u2');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Kurt Cobain','Cantor e guitarrista da banda Nirvana.','www.nirvana.com','@nirvana');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Raul Seixas','Cantor e compositor brasileiro conhecido como Pai do Rock Nacional.','www.raulseixas.com.br','@raulseixasoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (16,'Pitty','Cantora e compositora brasileira destaque do rock nacional.','www.pitty.com.br','@pitty');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (299,'Eminem','Rapper norte-americano considerado um dos maiores da história.','www.eminem.com','@eminem');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (299,'Tupac Shakur','Rapper norte-americano referência do hip hop mundial.','www.2pac.com','@2pac');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (299,'Jay-Z','Rapper e empresário norte-americano de grande influência cultural.','www.rocnation.com','@jayz');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (299,'Kendrick Lamar','Rapper premiado e reconhecido por suas letras profundas.','www.kendricklamar.com','@kendricklamar');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (299,'Drake','Cantor e rapper canadense de enorme sucesso mundial.','www.drakeofficial.com','@champagnepapi');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (298,'Bob Marley','Cantor jamaicano considerado o maior ícone do reggae.','www.bobmarley.com','@bobmarley');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Caetano Veloso','Cantor e compositor baiano um dos fundadores do Tropicalismo.','www.caetanoveloso.com.br','@caetanoveloso');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Gilberto Gil','compositor e ex-ministro da cultura brasileiro.','www.gilbertogil.com.br','@gilbertogil');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Maria Bethânia','Cantora brasileira considerada uma das maiores intérpretes do país.','www.mariabethania.com.br','@mariabethaniaoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Chico Buarque','compositor e escritor brasileiro.','www.chicobuarque.com.br','@chicobuarque');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Djavan','Cantor e compositor brasileiro de reconhecimento internacional.','www.djavan.com.br','@djavanoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Milton Nascimento','Cantor e compositor brasileiro conhecido mundialmente.','www.miltonnascimento.com.br','@miltonbitucanascimento');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Lenine','Cantor e compositor pernambucano premiado internacionalmente.','www.lenine.com.br','@lenineoficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Marisa Monte','Cantora e compositora brasileira de grande sucesso.','www.marisamonte.com.br','@marisamonte');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Adriana Calcanhotto','Cantora e compositora brasileira.','www.adrianacalcanhotto.com.br','@acalcanhotto');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (179,'Zeca Baleiro','Cantor e compositor brasileiro.','www.zecabaleiro.com.br','@zecabaleiro');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Louis Armstrong','Trompetista e cantor norte-americano pioneiro do jazz.','www.louisarmstrong.com','@louisarmstrong');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Miles Davis','Trompetista e compositor considerado um dos maiores nomes do jazz.','www.milesdavis.com','@milesdavis');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'John Coltrane','Saxofonista norte-americano referência mundial do jazz.','www.johncoltrane.com','@johncoltrane');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Duke Ellington','Pianista e compositor norte-americano.','www.dukeellington.com','@dukeellington');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Charlie Parker','Saxofonista criador do bebop.','www.charlieparker.com','@charlieparker');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Ella Fitzgerald','Cantora norte-americana conhecida como First Lady of Song.','www.ellafitzgerald.com','@ellafitzgerald');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Billie Holiday','Cantora norte-americana ícone do jazz.','www.billieholiday.com','@billieholiday');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Herbie Hancock','Pianista e compositor norte-americano.','www.herbiehancock.com','@herbiehancock');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Diana Krall','Cantora e pianista canadense.','www.dianakrall.com','@dianakrall');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (69,'Norah Jones','Cantora norte-americana vencedora de diversos Grammys.','www.norahjones.com','@norahjones');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'B.B. King','Guitarrista e cantor conhecido como Rei do Blues.','www.bbking.com','@bbking');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Muddy Waters','Cantor e guitarrista pioneiro do blues moderno.','www.muddywaters.com','@muddywaters');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Buddy Guy','Guitarrista norte-americano referência do blues.','www.buddyguy.com','@buddyguy');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'John Lee Hooker','Cantor e guitarrista norte-americano.','www.johnleehooker.com','@johnleehooker');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Albert King','Guitarrista influente do blues.','www.albertking.com','@albertking');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Stevie Ray Vaughan','Guitarrista norte-americano de grande influência.','www.srv.com','@stevierayvaughan');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Robert Johnson','Músico lendário do Delta Blues.','www.robertjohnson.com','@robertjohnson');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Eric Clapton','Cantor e guitarrista britânico.','www.ericclapton.com','@ericclapton');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Joe Bonamassa','Guitarrista e cantor norte-americano.','www.jbonamassa.com','@joebonamassa');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (60,'Keb Mo','Cantor e guitarrista vencedor do Grammy.','www.kebmo.com','@kebmo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'David Guetta','DJ e produtor francês.','www.davidguetta.com','@davidguetta');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Tiesto','DJ holandês de fama mundial.','www.tiesto.com','@tiesto');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Armin van Buuren','DJ holandês especialista em trance.','www.arminvanbuuren.com','@arminvanbuuren');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Martin Garrix','DJ e produtor holandês.','www.martingarrix.com','@martingarrix');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Alok','DJ brasileiro de reconhecimento internacional.','www.aloklive.com','@alok');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Vintage Culture','DJ brasileiro destaque mundial.','www.vintageculture.com','@vintageculture');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Calvin Harris','DJ e produtor escocês.','www.calvinharris.com','@calvinharris');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Avicii','DJ sueco responsável por sucessos globais.','www.avicii.com','@avicii');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Steve Aoki','DJ e produtor norte-americano.','www.steveaoki.com','@steveaoki');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (95,'Skrillex','DJ norte-americano referência do dubstep.','www.skrillex.com','@skrillex');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Johann Sebastian Bach','Compositor alemão do período barroco.','www.bach.com','@bach');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Wolfgang Mozart','Compositor austríaco do período clássico.','www.mozart.com','@mozart');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Ludwig Beethoven','Compositor alemão referência mundial da música clássica.','www.beethoven.com','@beethoven');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Antonio Vivaldi','Compositor italiano autor de As Quatro Estações.','www.vivaldi.com','@vivaldi');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Frédéric Chopin','Compositor e pianista polonês.','www.chopin.com','@chopin');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Johannes Brahms','Compositor alemão do romantismo.','www.brahms.com','@brahms');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Tchaikovsky','Compositor russo renomado mundialmente.','www.tchaikovsky.com','@tchaikovsky');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Franz Schubert','Compositor austríaco.','www.schubert.com','@schubert');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Richard Wagner','Compositor alemão famoso por suas óperas.','www.wagner.com','@wagner');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (83,'Giuseppe Verdi','Compositor italiano de óperas.','www.verdi.com','@verdi');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Fernandinho','Cantor e pastor brasileiro.','www.fernandinho.com.br','@fernandinhoepaula');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Aline Barros','Cantora gospel brasileira premiada.','www.alinebarros.com.br','@alinebarros');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Gabriela Rocha','Cantora brasileira de música cristã contemporânea.','www.gabrielarocha.com.br','@gabrielarocha77');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Bruna Karla','Cantora gospel brasileira.','www.brunakarla.com.br','@brunakarla');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'André Valadão','Cantor e pastor brasileiro.','www.andrevaladao.com','@andrevaladao');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Cassiane','Cantora gospel brasileira.','www.cassiane.com.br','@cassiane');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Eyshila','Cantora gospel brasileira.','www.eyshila.com.br','@eyshila');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Isadora Pompeo','Cantora cristã contemporânea.','www.isadorapompeo.com.br','@isadorapompeo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Diante do Trono','Grupo brasileiro de louvor e adoração.','www.diantedotrono.com','@diantedotrono');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (225,'Preto no Branco','Banda brasileira de música gospel.','www.pretonobranco.com.br','@pretonobranco');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'BTS','Grupo sul-coreano de enorme sucesso mundial.','www.bts.ibighit.com','@bts.bighitofficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Blackpink','Grupo feminino sul-coreano de sucesso global.','www.blackpinkofficial.com','@blackpinkofficial');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'EXO','Grupo sul-coreano formado pela SM Entertainment.','www.exo.smtown.com','@weareone.exo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Twice','Grupo feminino sul-coreano.','www.twice.jype.com','@twicetagram');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Stray Kids','Grupo masculino sul-coreano.','www.straykids.jype.com','@realstraykids');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Seventeen','Grupo sul-coreano de treze integrantes.','www.seventeen-17.com','@saythename_17');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Red Velvet','Grupo feminino sul-coreano.','www.redvelvet.smtown.com','@redvelvet.smtown');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'NewJeans','Grupo feminino sul-coreano.','www.newjeans.kr','@newjeans_official');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'Aespa','Grupo feminino sul-coreano.','www.aespa.com','@aespa_official');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (13,'BigBang','Grupo masculino sul-coreano pioneiro do gênero.','www.ygfamily.com','@bigbang_official');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (169,'Shakira','Cantora colombiana de sucesso mundial.','www.shakira.com','@shakira');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (169,'Ricky Martin','Cantor porto-riquenho reconhecido internacionalmente.','www.rickymartin.com','@ricky_martin');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (169,'Luis Fonsi','Cantor porto-riquenho conhecido por Despacito.','www.luisfonsi.com','@luisfonsi');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (169,'Enrique Iglesias','Cantor espanhol de sucesso internacional.','www.enriqueiglesias.com','@enriqueiglesias');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (162,'J Balvin','Cantor colombiano.','www.jbalvin.com','@jbalvin');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (162,'Maluma','Cantor colombiano de fama mundial.','www.maluma.online','@maluma');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (162,'Bad Bunny','Cantor porto-riquenho fenômeno global.','www.badbunny.com','@badbunnypr');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (162,'Karol G','Cantora colombiana premiada.','www.karolg.com','@karolg');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (162,'Daddy Yankee','Cantor porto-riquenho pioneiro do reggaeton.','www.daddyyankee.com','@daddyyankee');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (159,'Marc Anthony','Cantor norte-americano de origem porto-riquenha.','www.marcanthonyonline.com','@marcanthony');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Matuê','Cantor e compositor brasileiro.','www.30praum.com.br','@matue');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Teto','Cantor brasileiro do gênero trap.','www.30praum.com.br','@tetoin');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'WIU','Cantor e produtor brasileiro.','www.30praum.com.br','@wiu');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Veigh','Cantor brasileiro em ascensão.','www.veigh.com.br','@veigh');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Orochi','Rapper brasileiro.','www.orochi.com.br','@orochi');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Filipe Ret','Rapper e compositor brasileiro.','www.filiperet.com.br','@filiperet');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Derek','Cantor brasileiro integrante da Recayd Mob.','www.recaydmob.com','@derek');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Future','Rapper norte-americano referência do trap.','www.futurefreebandz.com','@future');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'Travis Scott','Rapper norte-americano de enorme sucesso.','www.travisscott.com','@travisscott');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (131,'21 Savage','Rapper britânico-americano.','www.21savage.com','@21savage');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (209,'João Gomes','Cantor pernambucano destaque nacional.','www.joaogomes.com.br','@joaogomescantor');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (209,'Vitor Fernandes','Cantor brasileiro de piseiro.','www.vitorfernandes.com.br','@vitorfernandes');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (209,'Zé Vaqueiro','Cantor brasileiro de forró e piseiro.','www.zevaqueiro.com.br','@zevaqueiro');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (209,'Nattan','Cantor cearense de sucesso.','www.nattan.com.br','@nattan');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (209,'Mari Fernandez','Cantora brasileira destaque do gênero.','www.marifernandez.com.br','@marifernandez');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (210,'Pablo','Cantor baiano conhecido como Rei da Sofrência.','www.pablo.com.br','@pablo');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (210,'Tayrone','Cantor baiano de arrocha.','www.tayrone.com.br','@tayrone');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (210,'Unha Pintada','Cantor sergipano de arrocha.','www.unhapintada.com.br','@unhapintada');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (210,'Silvanno Salles','Cantor baiano de música romântica.','www.silvannosalles.com.br','@silvannosalles');
INSERT INTO tb_artista (id_genero,nome,biografia,site,instagram) VALUES (210,'Toque Dez','Banda baiana de arrocha.','www.toquedez.com.br','@toquedez');